USE DATABASE COVID_ANALYTICS;

-- checking whether data was successfully ingested
SELECT * FROM EXTERNAL_DATA.COUNTRY_DEMOGRAPHICS
LIMIT 100;

SELECT COUNT(*)
FROM EXTERNAL_DATA.COUNTRY_DEMOGRAPHICS;


CREATE SCHEMA IF NOT EXISTS COVID_ANALYTICS.ANALYTICS;

-- creating a view based on JHU_COVID_19 but with different granularity
CREATE OR REPLACE VIEW ANALYTICS.COVID_YEARLY AS
SELECT
    COUNTRY_REGION,
    YEAR(DATE) AS YEAR,
    SUM(
        CASE
            WHEN CASE_TYPE = 'Confirmed' THEN DIFFERENCE
            ELSE 0
        END
    ) AS CONFIRMED_CASES,
    SUM(
        CASE
            WHEN CASE_TYPE = 'Deaths' THEN DIFFERENCE
            ELSE 0
        END
    ) AS DEATHS
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.JHU_COVID_19
WHERE YEAR(DATE) BETWEEN 2020 AND 2023
GROUP BY
    COUNTRY_REGION,
    YEAR(DATE);

-- investigate new view
SELECT * FROM ANALYTICS.COVID_YEARLY
LIMIT 100;

SELECT COUNT(*) FROM ANALYTICS.COVID_YEARLY;

-- merge COVID_YEARLY and COUNTRY_DEMOGRAPHICS tables to enable more broad analysis
CREATE OR REPLACE VIEW ANALYTICS.COVID_DEMOGRAPHIC_ANALYSIS AS
SELECT
    c.COUNTRY_REGION,
    c.YEAR,
    c.CONFIRMED_CASES,
    c.DEATHS,
    d.POPULATION,
    d.POPULATION_DENSITY,
    d.GDP_PER_CAPITA,
    NTILE(4) OVER (
        PARTITION BY c.YEAR
        ORDER BY d.POPULATION_DENSITY
    ) AS DENSITY_QUARTILE,
    NTILE(4) OVER (
        PARTITION BY c.YEAR
        ORDER BY d.GDP_PER_CAPITA
    ) AS GDP_QUARTILE,
    ROUND(c.CONFIRMED_CASES / NULLIF(d.POPULATION, 0) * 100000,
        2
    ) AS CASES_PER_100K,
    ROUND(
        c.DEATHS / NULLIF(d.POPULATION, 0) * 100000,
        2
    ) AS DEATHS_PER_100K,
    ROUND(
        c.DEATHS / NULLIF(c.CONFIRMED_CASES, 0) * 100,
        2
    ) AS CASE_FATALITY_RATE
FROM ANALYTICS.COVID_YEARLY c
LEFT JOIN EXTERNAL_DATA.COUNTRY_DEMOGRAPHICS d
    ON c.COUNTRY_REGION = d.COUNTRY
    AND c.YEAR = d.YEAR;

SELECT COUNT(*) FROM ANALYTICS.COVID_DEMOGRAPHIC_ANALYSIS;

SELECT * FROM ANALYTICS.COVID_DEMOGRAPHIC_ANALYSIS
LIMIT 100;

-- get the number of matched rows
SELECT
    COUNT(*) AS total_rows,
    COUNT(POPULATION) AS matched_population,
    COUNT(POPULATION_DENSITY) AS matched_density,
    COUNT(GDP_PER_CAPITA) AS matched_gdp
FROM COVID_ANALYTICS.ANALYTICS.COVID_DEMOGRAPHIC_ANALYSIS;

-- aggregate by year and quartile to distinguish between countries 
-- with different levels of population density 
SELECT
    YEAR,
    DENSITY_QUARTILE,
    ROUND(AVG(CASES_PER_100K), 2) AS AVG_CASES_PER_100K,
    ROUND(AVG(DEATHS_PER_100K), 2) AS AVG_DEATHS_PER_100K
FROM ANALYTICS.COVID_DEMOGRAPHIC_ANALYSIS
GROUP BY YEAR, DENSITY_QUARTILE
ORDER BY YEAR, DENSITY_QUARTILE;

SELECT
    YEAR,
    GDP_QUARTILE,
    ROUND(AVG(DEATHS_PER_100K), 2) AS AVG_DEATHS_PER_100K
FROM ANALYTICS.COVID_DEMOGRAPHIC_ANALYSIS
GROUP BY YEAR, GDP_QUARTILE
ORDER BY YEAR, GDP_QUARTILE;