SELECT CURRENT_ORGANIZATION_NAME();
SELECT CURRENT_ACCOUNT_NAME();
SELECT CURRENT_ACCOUNT();

SELECT
    COUNTRY_REGION,
    YEAR(DATE) AS YEAR,
    SUM(DIFFERENCE) AS CONFIRMED_CASES
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.JHU_COVID_19
WHERE CASE_TYPE = 'Confirmed'
GROUP BY COUNTRY_REGION, YEAR(DATE)
ORDER BY YEAR, CONFIRMED_CASES DESC;

SELECT
    COUNTRY_REGION,
    YEAR,
    CONFIRMED_CASES
FROM COVID_ANALYTICS.ANALYTICS.COVID_DEMOGRAPHIC_ANALYSIS
ORDER BY YEAR, CONFIRMED_CASES DESC;

-- Column pruning
SELECT *
FROM COVID_ANALYTICS.ANALYTICS.COVID_DEMOGRAPHIC_ANALYSIS
WHERE YEAR = 2022;

SELECT
    COUNTRY_REGION,
    CASES_PER_100K,
    DEATHS_PER_100K
FROM COVID_ANALYTICS.ANALYTICS.COVID_DEMOGRAPHIC_ANALYSIS
WHERE YEAR = 2022;

-- Micro-partition pruning

--broad
SELECT
    COUNTRY_REGION,
    DATE,
    DIFFERENCE
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.JHU_COVID_19
WHERE CASE_TYPE = 'Confirmed';

--selective
SELECT
    COUNTRY_REGION,
    DATE,
    DIFFERENCE
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.JHU_COVID_19
WHERE CASE_TYPE = 'Confirmed'
  AND COUNTRY_REGION = 'Lithuania'
  AND DATE >= '2022-01-01'
  AND DATE < '2023-01-01';

-- Result cache
SELECT
    COUNTRY_REGION,
    YEAR,
    CASES_PER_100K,
    DEATHS_PER_100K
FROM COVID_ANALYTICS.ANALYTICS.COVID_DEMOGRAPHIC_ANALYSIS
WHERE YEAR = 2022
ORDER BY CASES_PER_100K DESC;