SELECT *
FROM (
    SELECT
        DATE,
        SUM(DIFFERENCE) AS DAILY_CASES
    FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.JHU_COVID_19
    WHERE COUNTRY_REGION = 'Lithuania'
      AND CASE_TYPE = 'Confirmed'
      AND DIFFERENCE >= 0
    GROUP BY DATE
)
MATCH_RECOGNIZE (
    ORDER BY DATE

    MEASURES
        MATCH_NUMBER() AS PATTERN_ID,
        FIRST(DATE) AS START_DATE,
        LAST(DATE) AS END_DATE,
        FIRST(DAILY_CASES) AS START_CASES,
        LAST(DAILY_CASES) AS END_CASES,
        COUNT(*) AS DAYS_IN_PATTERN

    ONE ROW PER MATCH

    PATTERN (
        START_ROW INCREASE INCREASE+
    )

    DEFINE
        INCREASE AS DAILY_CASES > LAG(DAILY_CASES)
)
ORDER BY START_DATE
LIMIT 10;


SELECT *
FROM (
    SELECT
        DATE,
        SUM(DIFFERENCE) AS DAILY_CASES
    FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.JHU_COVID_19
    WHERE COUNTRY_REGION = 'Lithuania'
      AND CASE_TYPE = 'Confirmed'
      AND DIFFERENCE >= 0
    GROUP BY DATE
)
MATCH_RECOGNIZE (
    ORDER BY DATE

    MEASURES
        MATCH_NUMBER() AS PATTERN_ID,
        FIRST(DATE) AS START_DATE,
        LAST(DATE) AS END_DATE,
        FIRST(DAILY_CASES) AS START_CASES,
        LAST(DAILY_CASES) AS END_CASES,
        COUNT(*) AS DAYS

    ONE ROW PER MATCH

    PATTERN (START_ROW DOWN DOWN+)

    DEFINE
        DOWN AS DAILY_CASES < LAG(DAILY_CASES)
)
ORDER BY START_DATE;


SELECT *
FROM (
    SELECT
        DATE,
        SUM(DIFFERENCE) AS DAILY_CASES
    FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.JHU_COVID_19
    WHERE COUNTRY_REGION = 'Lithuania'
      AND CASE_TYPE = 'Confirmed'
      AND DIFFERENCE >= 0
    GROUP BY DATE
)
MATCH_RECOGNIZE (
    ORDER BY DATE

    MEASURES
        MATCH_NUMBER() AS PATTERN_ID,
        FIRST(DATE) AS START_DATE,
        LAST(DATE) AS END_DATE,
        FIRST(DAILY_CASES) AS START_CASES,
        LAST(DOWN.DAILY_CASES) AS LOWEST_CASES,
        LAST(DAILY_CASES) AS END_CASES,
        COUNT(*) AS DAYS

    ONE ROW PER MATCH

    PATTERN (START_ROW DOWN+ UP+)

    DEFINE
        DOWN AS DAILY_CASES < LAG(DAILY_CASES),
        UP AS DAILY_CASES > LAG(DAILY_CASES)
)
ORDER BY START_DATE
LIMIT 10;